Update hook, using media_buttons instead of media_buttons_context
10up/windows-azure-storage pull request #147
Opened 2021-09-21 12:01 UTC by debabratakarfa

### Description of the Change

`media_buttons_context`  hook has been deprecated, using `media_buttons` action instead.

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

- How did you verify that all new functionality works as expected?
- How did you verify that all changed functionality works as expected?
- How did you verify that the change has not introduced any regressions?

Describe the actions you performed (e.g., commands you ran, text you typed, buttons you clicked) and describe the results you observed.
-->

### Checklist:

- [x ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-09-21 18:37 UTC, jeffpaul commented
Pinging a couple folks here to see if one can help review this.  Once its passed code review we can look to milestone in a numbered release.  Thanks for the WP.org support issue and opening the PR @debabratakarfa!

2021-10-15 01:55 UTC, jeffpaul commented
@rickalee @colegeissinger @thrijith any feedback on your review here?

2021-10-15 18:25 UTC, NicoleGeissinger requested changes
The changes look good minus one spot that needs to be fixed. Once that is fixed I can approve this PR for merge.

2021-10-15 18:25 UTC, NicoleGeissinger commented on windows-azure-storage.php
> +add_filter( 'media_buttons', 'windows_azure_storage_media_buttons_context' );
@debabratakarfa we'll want to update the function name we are calling since our function name was also updated to reflect the updated filter name.

This should look like this `add_filter( 'media_buttons', 'windows_azure_storage_media_buttons' );`

2021-10-23 12:37 UTC, debabratakarfa commented on windows-azure-storage.php
> +add_filter( 'media_buttons', 'windows_azure_storage_media_buttons_context' );
Hi @colegeissinger 
Thanks, I will update it.

2021-10-28 16:13 UTC, NicoleGeissinger approved these changes

2021-10-28 16:13 UTC, NicoleGeissinger commented
Thank you! This looks good from my end!

2021-10-28 16:14 UTC, merged