Add PDF replacement feature
10up/windows-azure-storage pull request #220
Opened 2024-03-27 21:11 UTC by hugosolar

### Description of the Change
We've seen some situations where users want to replace a PDF file with an updated version (CV for example)
This PR adds to the plugin the ability to replace pdf files (for now) using a new method to copy the blob and replace it with the uploaded file.
There's a new method called `copy_media_to_blob_storage`  in helpers and also a new `copy_blob` method in the API client
this uses the Copy Blob operation described here: https://learn.microsoft.com/en-us/rest/api/storageservices/Copy-Blob

There's also a new button added in the media uploader that holds the workflow to replace the document

## Open discussion for addressing images
We should have a discussion on how to approach image replacements since an image of a different orientation can be uploaded and image sizes of the image to be replaced won't match, so I was thinking on two paths
-  Should we force the same image sizes from the replaced image so we can have backward compatibility in case those images are being called directly?
- Should we discard previous images and just replace thumbnails with the ones generated by the new image?

### How to test the Change
To test this:
- Go to the media screen in the admin dashboard (`wp-admin/upload.php`)
- Upload a PDF file
- Select the file and you'll see a "replace this media" button
- Click the button and select the file to upload (the view is restricted to just upload a file)
- Once it's uploaded click on the "Replace media" button below
- That will trigger the replacement of the main file and the thumbnails stored as meta fields

### Changelog Entry

> Added - New feature to replace PDF files at the blob storage level
> Fixed - Bug fix. Fixed a bug with the transient generated for displaying progress

### Credits
@hugosolar 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-04-01 21:24 UTC, jeffpaul commented
@hugosolar looks like failing e2e tests, could you check on those please?

2024-04-11 16:23 UTC, hugosolar commented
@jeffpaul I think this is related to the constants passed to Cypress related to the account name & key

here https://github.com/hugosolar/windows-azure-storage/blob/022290b32e875986dc4b790be6891c56ad736c2d/tests/cypress/e2e/settings.test.js#L12

On a previous PR, I remember we faced the same situation and @Sidsector9 was able to fix it
let me know otherwise

2024-04-17 14:28 UTC, rickalee requested changes

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-helper.php
> +			Windows_Azure_Rest_Api_Client::API_HEADER_MS_BLOB_CONTENT_TYPE  => $mime_type,
@hugosolar Where is this $mime-type being set at? I don't see in function or parameters?

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +				'html'  => '<button class="button-secondary" id="azure-media-replacement" onclick="replaceMedia(' . $post->ID . ');">' . esc_html__( 'Replace this media', 'windows-azure-storage' ) . '</button>',
@hugosolar Should we escape the $post->ID or use a sprintf here instead?

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +				die ( 'nope' );
@hugosolar Let's switch this to wp_die() and be more descriptive.

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +		wp_die();
@hugosolar Is this wp_die() necessary?

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +			return __( 'Cannot determine images IDs, aborting...', 'windows-azure-storage' );
@hugosolar Let's escape this translation in case bad .po/.mo file?

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +			return __( 'Path issues, aborting...', 'windows-azure-storage' );
@hugosolar Let's escape all __() please

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +			echo '<p>', sprintf( __( 'Error in uploading file. Error: %s', 'windows-azure-storage' ), esc_html( $e->getMessage() ) ), '</p>';
@hugosolar Can we add the <p> inside the sprintf() for readability please?

2024-04-17 14:28 UTC, rickalee commented on includes/class-windows-azure-replace-media.php
> +						echo '<p>', sprintf( __( 'Error in uploading file. Error: %s', 'windows-azure-storage' ), esc_html( $e->getMessage() ) ), '</p>';
@hugosolar Let's move <p> inside sprintf

2024-04-17 14:29 UTC, rickalee commented
@hugosolar  Some feedback to address and need to address the E2E tests.

2024-04-17 18:06 UTC, rickalee approved these changes

2024-04-23 18:49 UTC, merged