Add image replacement feature
10up/windows-azure-storage pull request #230
Opened 2024-05-27 22:49 UTC by hugosolar

### Description of the Change
Extending our previous feature to replace PDFs in #220 
Now I'm adding the feature to replace images.
The criteria to replace images is based on the image to be replaced, we're using it as a reference to handle metadata
Since we don't want to use GD or imagemagick to generate new sizes besides the ones that WordPress has already created.
We're considering intermediate image URLs being obtained using WordPress functions instead of the URL itself, that way we're not dealing with different sizes filenames (which most of the time doesn't match)

The workflow we're following is

- Selecting an image to be replaced
- Click "Replace this media"
- Select an image to replace
- The new image is going to be uploaded to Azure
- After that if "Replace media" is clicked:
  -  Replacing the main image
  - Delete the source blobs to avoid duplicates
  - Loop through the replacement's sizes in `_wp_attached_file` and copy those over to replace the location
  - We're doing the same with `windows_azure_storage_info` metafield
  - Then we delete the newest attachment 

https://drive.google.com/file/d/1vPuk_cYUdWrlGBY3bUkjxWTpZeYr-BTG/view

This plugin also fixes #184 ensuring we're processing an array with array_flip otherwise returning a WP_Error object

### How to test the Change
- Clone this branch to your local environment
- Follow the workflow in the video: https://drive.google.com/file/d/1vPuk_cYUdWrlGBY3bUkjxWTpZeYr-BTG/view

### Changelog Entry
> Added - New feature
Feature to replace images at the blob storage level

> Fixed - Bug fix
Fixed bug relate to the use of array_flip and not ensuring it was an actual arrat

### Credits
Props @hugosolar 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-06-03 20:49 UTC, jeffpaul commented
@rickalee looking to you / your team for review / approval here

2024-06-16 18:06 UTC, rickalee approved these changes, later dismissed

2024-06-16 18:07 UTC, rickalee commented
@hugosolar Approved. Looks great. Any considerations with Cache and configuration we need to document for other users of public plugin?

2024-06-17 18:43 UTC, hugosolar commented
@rickalee I've addressed cache issue by setting the blob properties cache to 30 segs
![Screenshot 2024-06-17 at 14 42 01](https://github.com/10up/windows-azure-storage/assets/894708/2b0a0ad8-3590-4f92-846c-6ea4ef88f592)

2024-06-17 19:22 UTC, rickalee approved these changes, later dismissed

2024-06-18 17:16 UTC, hugosolar commented
@jeffpaul the e2e error seems to come directly from `wp-env`
```
ERROR: for f505fb82f2963a5299b2972f47ad8834_mysql_1  'ContainerConfig'
Creating f505fb82f2963a5299b2972f47ad8834_tests-wordpress_1 ... done
Creating f505fb82f2963a5299b2972f47ad8834_tests-cli_1       ... 
Creating f505fb82f2963a5299b2972f47ad8834_tests-cli_1       ... done
[2378] Failed to execute script docker-compose

ERROR: for mysql  'ContainerConfig'
```

have you seen this before?
actually, we're using `@wordpress/env` `8.7.0` in the plugin and it's currently at `2.0.0` I can try to update that library and see how it goes

2024-06-18 17:20 UTC, dkotter commented
@hugosolar Yes, updating `@wordpress/env` to the latest should fix that particular issue, as we've ran across this on a few other plugins. Seems GitHub updated the `ubuntu-latest` image and this causes issues with wp-env if it's not running the latest

2024-06-18 19:53 UTC, hugosolar commented
@dkotter @jeffpaul I've updated `wp-env` and I can see the build is passing now
now it's failing on cypress tests since I'm pushing from a forked repository and secrets aren't available to accomplish those tests.
This has been fixed on my other PRs
let me know how can I help with this

2024-06-24 14:57 UTC, dkotter requested changes

2024-06-24 14:57 UTC, dkotter commented on includes/class-windows-azure-helper.php
> +	static public function copy_media_to_blob_storage( $container_name, $destination_path, $source_path, $mime_type, $account_name = '', $account_key = '', $cache = null ) {
Since we're adding a new function param here, we should document that in the docblock

2024-06-24 14:57 UTC, dkotter commented on includes/class-windows-azure-replace-media.php
> +	private $container_name = '';
Can we add a docblock on this property?

2024-06-24 14:57 UTC, dkotter commented on includes/class-windows-azure-replace-media.php
> +		$this->allowed_types = apply_filters(
Not sure if we do this consistently in this plugin but would be great to add proper hook documentation here: https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters

2024-06-24 14:57 UTC, dkotter commented on includes/class-windows-azure-replace-media.php
> +			// $this->delete_previous_thumbnails( $source_data );
Can we remove this?

2024-06-24 14:57 UTC, dkotter commented on includes/class-windows-azure-replace-media.php
> +		$target_filename  = $target_sizes['meta_data']['file'];
Wondering if we need to be more defensive here? For both `$source_sizes` and `$target_sizes`, will these always be arrays and will the keys we want always exist? Or do we need to check for those before proceeding?

2024-06-24 14:57 UTC, dkotter commented on includes/class-windows-azure-replace-media.php
> +		add_action( 'wp_ajax_nopriv_azure-storage-media-replace', array( $this, 'process_media_replacement' ) );
I know this is not part of this PR but does this need to fire on the `nopriv` hook? Seems like replacing media is something that should only be triggered by a logged in user

2024-06-24 15:52 UTC, hugosolar commented on includes/class-windows-azure-replace-media.php
> +		$target_filename  = $target_sizes['meta_data']['file'];
@dkotter since this array is made above, it stores WordPress default `_wp_attachment_metadata` so it's always expected to exist if it's a valid attachment. Although I agree with the extra check because we never knows if we're about to handle an invalid attachment or a similar situation. 
I've added some extra checks to bail early

2024-06-24 16:01 UTC, dkotter submitted a review, later dismissed

2024-06-26 18:15 UTC, jeffpaul commented
Note I'm holding for @rickalee's review before merging here

2024-07-09 15:34 UTC, rickalee approved these changes

2024-07-09 15:35 UTC, rickalee commented
@jeffpaul @hugosolar @dkotter Approved after a few updates by Hugo.

2024-07-09 17:43 UTC, jeffpaul commented
@hugosolar mind checking on the e2e failures before this gets merged in?

2024-07-09 18:48 UTC, hugosolar commented
@jeffpaul as far as I can see, it's failing because I'm pushing this PR from my fork
and it doesn't have environment keys for Blob storage cypress tests. Tried to add those environment variables to my fork but doesn't seem to be working.

2024-07-09 19:16 UTC, merged