Change the function else condition so that can use in existing project
10up/windows-azure-storage pull request #70
Opened 2019-01-29 07:41 UTC by creativehassan

I have changed the function because if someone want to use it in existing project and move all existing media to azure than can easily render media from azure all old and latest media files.

2019-02-19 19:03 UTC, allan23 commented
@creativehassan why change the function name?

2019-02-20 20:42 UTC, creativehassan commented
@allan23  No function name change just inner body of function is modified for existing projects to use this plugin. 

Thanks

2019-02-20 20:44 UTC, allan23 commented
@creativehassan your code in your PR changes the name of the function from `windows_azure_storage_wp_get_attachment_url` to `edwards_azure_storage_wp_get_attachment_url()`.

2019-02-20 23:40 UTC, creativehassan commented
Ah my bad let me revert it. and make it same

2019-02-21 20:45 UTC, allan23 requested changes

2019-02-21 20:45 UTC, allan23 commented on windows-azure-storage.php
> +function edwards_azure_storage_wp_get_attachment_url( $url, $post_id ) {
Function name needs updated.

2019-04-01 19:49 UTC, jeffpaul commented
@creativehassan any updates on being able to revert the function name?

2019-09-05 14:52 UTC, jeffpaul commented
@creativehassan any updates on being able to revert the function name?

2019-09-06 09:51 UTC, creativehassan commented
Hi Jeff Paul, I was much busy some where else. I just change the name of the function.

2019-11-14 21:01 UTC, jeffpaul commented
Moving this from the `4.3.0` release to `Future Release` to allow for more time to review the requested change here.

2022-05-11 03:20 UTC, jeffpaul commented
@rickalee this is a pretty long-standing PR, any chance you or someone on the team can get this through review and off to merge?

2024-01-02 18:59 UTC, jeffpaul commented
@rickalee @colegeissinger are you able to give this a final code review/test to get this into a release or should we close out this PR as no longer actionable/desired?

2024-01-11 18:24 UTC, jeffpaul commented
Closing this as not currently actionable, but open to having this re-opened if someone is able to own the completion and review of this.

2024-01-11 18:24 UTC, closed without merging